#!/usr/bin/env perl
use Mojo::Base -strict, -signatures, -async_await;
use Mojo::Promise;
use Mojo::Util 'dumper';
use lib "lib";
use App;
use Req;

my $app = App->new;

my $exit = 0;

Mojo::Promise
    ->all(
        $app->install(Req->new('App::cpm')),
        $app->install(Req->new('App::FatPacker')),
    )->catch(
        sub (@err) { warn dumper \@err; $exit = 1 }
    )->wait;

exit $exit;
